import { Project, NewsItem } from "@/types/project";

type DemoProjectSeed = Pick<
  Project,
  "id" | "slug" | "title" | "location" | "year" | "typology" | "category" | "subcategory" | "sizeM2" | "heroImage" | "description"
>;

const demoImage = (photoId: string) =>
  `https://images.unsplash.com/${photoId}?auto=format&fit=crop&w=1200&q=85`;

const createDemoProject = (project: DemoProjectSeed): Project => ({
  ...project,
  client: "Plane Architect Studio",
  status: "Concept",
  aspectRatio: "4 / 3",
});

export const PROJECTS: Project[] = [
  {
    id: "1",
    slug: "dhaka-contemporary-art-center",
    title: "Dhaka Contemporary Art Center",
    location: "Dhaka, Bangladesh",
    year: "2026",
    client: "National Arts Trust & Ministry of Cultural Affairs",
    typology: "Culture",
    category: "architecture",
    subcategory: "culture",
    sizeM2: "48,000",
    sizeFt2: "516,000",
    status: "Completed",
    aspectRatio: "16 / 9",
    heroImage:
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1600&q=85",
    iconSvg: `<svg viewBox="0 0 52 52" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="10" y="10" width="32" height="32" stroke="white" stroke-width="2.5"/><circle cx="26" cy="26" r="8" fill="white"/></svg>`,
    quote:
      "Architecture in the Bengal delta must breathe with water, light, and monsoon rhythm. By elevating the galleries above high-water thresholds and carving perforated terracotta screen walls, the center transforms tropical climatic reality into luminous spatial poetry.",
    quoteAuthor: "Plane Architect",
    quoteAuthorRole: "Design Principal, Plane Architect Dhaka",
    description:
      "A flagship cultural landmark positioned along the revitalized waterfront of Dhaka. Featuring a series of interlocking exhibition pavilions wrapped in locally fired perforated terracotta, the complex celebrates Bangladesh's artistic heritage while offering climate-resilient civic gathering halls.",
    awards: ["South Asian Architecture Excellence Award 2025", "International Civic Architecture Gold"],
    collaborators: ["Bengal Structural Consultants", "Delta Climate Labs", "Arup Façades"],
    diagrams: [
      {
        step: "01",
        title: "Site & Floodplain Alignment",
        description: "The 350-meter waterfront boundary establishes the primary axis, aligned with dominant seasonal breeze vectors from the Bay of Bengal.",
        image:
          "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1000&q=80",
      },
      {
        step: "02",
        title: "Plinth Elevation",
        description: "Elevating the primary public concourse 3.5 meters above maximum fifty-year flood levels creates a secure dry-season amphitheater.",
        image:
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
      },
      {
        step: "03",
        title: "Perforated Terracotta Skin",
        description: "Layering the building envelope with porous brick jali screens reduces solar heat gain by 68% while sustaining natural cross-ventilation.",
        image:
          "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1000&q=80",
      },
      {
        step: "04",
        title: "Courtyard Microclimates",
        description: "Internal shaded water courtyards induce evaporative cooling, lowering ambient gallery temperatures naturally.",
        image:
          "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80",
      },
      {
        step: "05",
        title: "Monsoon Roof Scape",
        description: "Deep overhangs and inverted hyperbolic roofs collect 100% of rainwater for year-round cooling and landscape hydration.",
        image:
          "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80",
      },
      {
        step: "06",
        title: "Public Promenade",
        description: "The rooftop landscape steps gradually down to the riverbank, returning public green space back to the citizens of Dhaka.",
        image:
          "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1000&q=80",
      },
    ],
    gallery: [
      {
        url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1600&q=85",
        caption: "Main waterfront facade with illuminated perforated terracotta screens",
        aspectRatio: "16 / 9",
      },
      {
        url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85",
        caption: "Central atrium with filtered northern daylight and reflection pool",
        aspectRatio: "16 / 9",
      },
      {
        url: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1600&q=85",
        caption: "Elevated sculpture courtyard connecting east and west galleries",
        aspectRatio: "16 / 9",
      },
    ],
    credits: [
      {
        role: "Principal Architect",
        people: ["Plane Architect Studio"],
      },
      {
        role: "Project Director",
        people: ["K. Rahman", "S. Chowdhury"],
      },
      {
        role: "Design Team",
        people: ["N. Hasan", "T. Ahmed", "M. Karim", "A. Siddique"],
      },
    ],
  },
  {
    id: "2",
    slug: "gulshan-botanical-pavilion",
    title: "Gulshan Botanical Pavilion",
    location: "Dhaka, Bangladesh",
    year: "2025",
    client: "Dhaka Urban Green Trust",
    typology: "Landscape",
    category: "landscape",
    subcategory: "parks",
    sizeM2: "14,500",
    sizeFt2: "156,000",
    status: "Completed",
    aspectRatio: "16 / 10",
    heroImage:
      "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=1600&q=85",
    iconSvg: `<svg viewBox="0 0 52 52" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M26 10C16 18 12 30 16 38C20 44 32 44 36 38C40 30 36 18 26 10Z" stroke="white" stroke-width="2.5"/><line x1="26" y1="18" x2="26" y2="42" stroke="white" stroke-width="2"/></svg>`,
    quote:
      "In a dense metropolis, nature cannot be merely a decorative fringe. It must be woven as an active botanical lung that filters urban dust, regulates microclimate, and provides sanctuary.",
    quoteAuthor: "Plane Architect",
    quoteAuthorRole: "Design Principal, Plane Architect",
    description:
      "A biophilic sanctuary situated in Gulshan, Dhaka, comprising stepped botanical terraces, native wetland gardens, and open-air timber pavilions for community contemplation.",
    gallery: [
      {
        url: "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=1600&q=85",
        caption: "Verdant stepped terraces framing the urban reflection lake",
        aspectRatio: "16 / 10",
      },
    ],
    credits: [
      {
        role: "Landscape Lead",
        people: ["Plane Architect Landscape Division"],
      },
    ],
  },
  {
    id: "3",
    slug: "brahmaputra-ecological-campus",
    title: "Brahmaputra Ecological Campus",
    location: "Mymensingh, Bangladesh",
    year: "2025",
    client: "Agricultural Research Foundation",
    typology: "Education",
    category: "architecture",
    subcategory: "education",
    sizeM2: "62,000",
    sizeFt2: "667,000",
    status: "In Progress",
    aspectRatio: "16 / 9",
    heroImage:
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1600&q=85",
    iconSvg: `<svg viewBox="0 0 52 52" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12 40L26 12L40 40H12Z" stroke="white" stroke-width="2.5"/><circle cx="26" cy="30" r="4" fill="white"/></svg>`,
    quote:
      "Agrarian landscapes and cutting-edge biotechnology labs meet under a continuous undulating bamboo timber superstructure, blurring the boundary between indoor laboratory and field research.",
    quoteAuthor: "Plane Architect",
    quoteAuthorRole: "Plane Architect Studio",
    description:
      "An advanced agro-climatic university and research campus on the banks of the Brahmaputra River, designed with mass engineered bamboo, rammed earth, and solar canopies.",
    gallery: [
      {
        url: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1600&q=85",
        caption: "Main research complex with natural daylit timber galleries",
        aspectRatio: "16 / 9",
      },
    ],
    credits: [
      {
        role: "Lead Architects",
        people: ["Plane Architect Studio"],
      },
    ],
  },
  {
    id: "4",
    slug: "meghna-riverside-sanctuary",
    title: "Meghna Riverside Sanctuary",
    location: "Narayanganj, Bangladesh",
    year: "2024",
    client: "Heritage Conservation Trust",
    typology: "Hospitality",
    category: "architecture",
    subcategory: "hospitality",
    sizeM2: "18,200",
    sizeFt2: "195,000",
    status: "Completed",
    aspectRatio: "16 / 10",
    heroImage:
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1600&q=85",
    iconSvg: `<svg viewBox="0 0 52 52" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M10 26C18 20 34 20 42 26C34 32 18 32 10 26Z" stroke="white" stroke-width="2.5"/><circle cx="26" cy="26" r="3" fill="white"/></svg>`,
    quote:
      "Riverine life is the primordial heartbeat of Bengal. The retreat rests gently along the Meghna riverbanks, touching the earth lightly on slender pilotis to permit seasonal tidal ebb and flow.",
    quoteAuthor: "Plane Architect",
    quoteAuthorRole: "Plane Architect Studio",
    description:
      "A low-impact eco-resort and wellness haven surrounded by ancient river canals, utilizing vernacular hand-woven thatch, local red clay, and floating timber decks.",
    gallery: [
      {
        url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1600&q=85",
        caption: "Riverside pavilions bathed in dawn mist",
        aspectRatio: "16 / 10",
      },
    ],
    credits: [
      {
        role: "Principal Architects",
        people: ["Plane Architect Studio"],
      },
    ],
  },
  {
    id: "5",
    slug: "sylhet-rain-pavilion",
    title: "Sylhet Rain Pavilion",
    location: "Sylhet, Bangladesh",
    year: "2024",
    client: "Surma Botanical Society",
    typology: "Culture",
    category: "architecture",
    subcategory: "culture",
    sizeM2: "6,400",
    sizeFt2: "68,800",
    status: "Completed",
    aspectRatio: "16 / 9",
    heroImage:
      "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1600&q=85",
    iconSvg: `<svg viewBox="0 0 52 52" fill="none" xmlns="http://www.w3.org/2000/svg"><line x1="26" y1="10" x2="26" y2="42" stroke="white" stroke-width="3"/><path d="M14 22L26 10L38 22" stroke="white" stroke-width="3"/></svg>`,
    quote:
      "Rain is not an adversary to be sealed away, but a sensory symphony to be framed, celebrated, and channeled into cascading fountains and lush moss courts.",
    quoteAuthor: "Plane Architect",
    quoteAuthorRole: "Plane Architect Studio",
    description:
      "An open-air pavilion in the misty tea hills of Sylhet celebrating monsoon rainfall through inverted bronze roof gullies and acoustic rainwater chambers.",
    gallery: [
      {
        url: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1600&q=85",
        caption: "Inverted canopy channeling rainwater into the central sunken court",
        aspectRatio: "16 / 9",
      },
    ],
    credits: [
      {
        role: "Design Lead",
        people: ["Plane Architect Studio"],
      },
    ],
  },
  {
    id: "6",
    slug: "apex-commercial-tower",
    title: "Apex Aerodynamic Tower",
    location: "Dhaka, Bangladesh",
    year: "2026",
    client: "Apex Financial Holdings",
    typology: "Work",
    category: "architecture",
    subcategory: "work",
    sizeM2: "85,000",
    sizeFt2: "914,000",
    status: "In Progress",
    aspectRatio: "16 / 10",
    heroImage:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=85",
    iconSvg: `<svg viewBox="0 0 52 52" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="14" y="8" width="24" height="36" stroke="white" stroke-width="2"/><line x1="14" y1="20" x2="38" y2="20" stroke="white" stroke-width="2"/><line x1="14" y1="32" x2="38" y2="32" stroke="white" stroke-width="2"/></svg>`,
    quote:
      "A skyscraper in tropical Dhaka must be an aerodynamic kite. By sculpting the tower to dissipate cyclones and embedding vertical sky gardens every three stories, we re-invent workplace well-being in South Asia.",
    quoteAuthor: "Plane Architect",
    quoteAuthorRole: "Design Principal, Plane Architect Dhaka",
    description:
      "A 42-story commercial tower in Motijheel, Dhaka, with an aerodynamic curved silhouette that reduces wind vortex shedding and integrates landscaped double-height sky gardens.",
    gallery: [
      {
        url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=85",
        caption: "Glazed corner terraces overlooking the skyline of Dhaka",
        aspectRatio: "16 / 10",
      },
    ],
    credits: [
      {
        role: "Partners",
        people: ["Plane Architect Studio"],
      },
    ],
  },
  {
    id: "7",
    slug: "sonargaon-cultural-archive",
    title: "Sonargaon Cultural Archive",
    location: "Sonargaon, Bangladesh",
    year: "2023",
    client: "Folk Art and Crafts Foundation",
    typology: "Culture",
    category: "architecture",
    subcategory: "culture",
    sizeM2: "11,800",
    sizeFt2: "127,000",
    status: "Completed",
    aspectRatio: "16 / 9",
    heroImage:
      "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=85",
    iconSvg: `<svg viewBox="0 0 52 52" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="12" y="14" width="28" height="24" stroke="white" stroke-width="2"/><line x1="12" y1="26" x2="40" y2="26" stroke="white" stroke-width="2"/></svg>`,
    quote:
      "Historic craftsmanship is not a nostalgic memory; it is an active architectural language of thermal mass, tactile earth, and human-scale detailing.",
    quoteAuthor: "Plane Architect",
    quoteAuthorRole: "Plane Architect Studio",
    description:
      "Dedicated to preserving Bengal's centuries-old weaving, brass craft, and terracotta heritage through climate-controlled archive vaults and public artisan workshops.",
    gallery: [
      {
        url: "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=85",
        caption: "Handmade brick vaults providing natural insulation to archive halls",
        aspectRatio: "16 / 9",
      },
    ],
    credits: [
      {
        role: "Lead Architects",
        people: ["Plane Architect Studio"],
      },
    ],
  },
  {
    id: "8",
    slug: "bengal-maritime-hub",
    title: "Bengal Maritime Innovation Hub",
    location: "Chittagong, Bangladesh",
    year: "2025",
    client: "Port Authority & Oceanographic Council",
    typology: "Infrastructure",
    category: "architecture",
    subcategory: "infrastructure",
    sizeM2: "38,000",
    sizeFt2: "409,000",
    status: "In Progress",
    aspectRatio: "16 / 9",
    heroImage:
      "https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1600&q=85",
    iconSvg: `<svg viewBox="0 0 52 52" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M10 34C18 30 34 30 42 34V18L26 12L10 18V34Z" stroke="white" stroke-width="2.5"/></svg>`,
    quote:
      "The maritime history of the Bay of Bengal shaped global trade routes for millennia. The hub's hull-inspired silhouette acts as a gateway to oceanic research and sustainable port innovation.",
    quoteAuthor: "Plane Architect",
    quoteAuthorRole: "Plane Architect Studio",
    description:
      "A coastal maritime research center and vessel navigation academy engineered with corrosion-resistant marine timber and seawater cooling exchange systems.",
    gallery: [
      {
        url: "https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1600&q=85",
        caption: "Marine research facility extending into Chittagong harbor waters",
        aspectRatio: "16 / 9",
      },
    ],
    credits: [
      {
        role: "Design Lead",
        people: ["Plane Architect Studio"],
      },
    ],
  },
  ...([
    {
      id: "9",
      slug: "sundarbans-field-station",
      title: "Sundarbans Field Station",
      location: "Khulna, Bangladesh",
      year: "2026",
      typology: "Education",
      category: "architecture",
      subcategory: "education",
      sizeM2: "4,800",
      heroImage: demoImage("photo-1511818966892-d7d671e672a2"),
      description: "Demo proposal for a raised research station that supports field teams while keeping the tidal forest floor open.",
    },
    {
      id: "10",
      slug: "old-dhaka-courtyard-house",
      title: "Old Dhaka Courtyard House",
      location: "Old Dhaka, Bangladesh",
      year: "2025",
      typology: "Residential",
      category: "architecture",
      subcategory: "residential",
      sizeM2: "1,250",
      heroImage: demoImage("photo-1600566753086-00f18fb6b3ea"),
      description: "Demo residential study reworking a narrow urban plot around a shaded courtyard and a layered brick facade.",
    },
    {
      id: "11",
      slug: "mymensingh-river-library",
      title: "Mymensingh River Library",
      location: "Mymensingh, Bangladesh",
      year: "2025",
      typology: "Culture",
      category: "architecture",
      subcategory: "culture",
      sizeM2: "3,600",
      heroImage: demoImage("photo-1600607687939-ce8a6c25118c"),
      description: "Demo civic library concept pairing a quiet reading courtyard with a shaded public edge along the river.",
    },
    {
      id: "12",
      slug: "cox-bazar-coastal-lodge",
      title: "Cox's Bazar Coastal Lodge",
      location: "Cox's Bazar, Bangladesh",
      year: "2026",
      typology: "Hospitality",
      category: "architecture",
      subcategory: "hospitality",
      sizeM2: "6,200",
      heroImage: demoImage("photo-1600585154340-be6161a56a0c"),
      description: "Demo low-rise retreat shaped around salt-resistant materials, cross-breezes, and protected garden courts.",
    },
    {
      id: "13",
      slug: "karnaphuli-exchange",
      title: "Karnaphuli Exchange",
      location: "Chattogram, Bangladesh",
      year: "2025",
      typology: "Work",
      category: "architecture",
      subcategory: "work",
      sizeM2: "21,000",
      heroImage: demoImage("photo-1486406146926-c627a92ad1ab"),
      description: "Demo workplace concept using deep external shade and shared terraces to connect offices with the port city.",
    },
    {
      id: "14",
      slug: "tejgaon-arts-workshop",
      title: "Tejgaon Arts Workshop",
      location: "Dhaka, Bangladesh",
      year: "2026",
      typology: "Exhibition",
      category: "interiors",
      subcategory: "exhibition",
      sizeM2: "2,100",
      heroImage: demoImage("photo-1600210492486-724fe5c67fb0"),
      description: "Demo adaptive interior for exhibitions, making, and informal gatherings within a converted industrial shell.",
    },
    {
      id: "15",
      slug: "gulshan-atelier-offices",
      title: "Gulshan Atelier Offices",
      location: "Dhaka, Bangladesh",
      year: "2025",
      typology: "Workplace",
      category: "interiors",
      subcategory: "workplace",
      sizeM2: "1,700",
      heroImage: demoImage("photo-1616486338812-3dadae4b4ace"),
      description: "Demo studio interior organized as a sequence of flexible team rooms around a shared material library.",
    },
    {
      id: "16",
      slug: "shonar-boat-lobby",
      title: "Shonar Boat Lobby",
      location: "Sylhet, Bangladesh",
      year: "2024",
      typology: "Hospitality",
      category: "interiors",
      subcategory: "hospitality",
      sizeM2: "860",
      heroImage: demoImage("photo-1600607687920-4e2a09cf159d"),
      description: "Demo guesthouse interior drawing on boat-building craft, warm timber, and a long view toward the garden.",
    },
    {
      id: "17",
      slug: "buriganga-wetland-park",
      title: "Buriganga Wetland Park",
      location: "Dhaka, Bangladesh",
      year: "2026",
      typology: "Parks",
      category: "landscape",
      subcategory: "parks",
      sizeM2: "32,000",
      heroImage: demoImage("photo-1470071459604-3b5ec3a7fe05"),
      description: "Demo landscape plan restoring a wetland edge with accessible walks, native planting, and seasonal flood zones.",
    },
    {
      id: "18",
      slug: "sylhet-canopy-garden",
      title: "Sylhet Canopy Garden",
      location: "Sylhet, Bangladesh",
      year: "2025",
      typology: "Gardens",
      category: "landscape",
      subcategory: "gardens",
      sizeM2: "9,400",
      heroImage: demoImage("photo-1441974231531-c6227db76b6e"),
      description: "Demo botanical garden tracing shaded paths through a layered canopy of native trees and understory plants.",
    },
    {
      id: "19",
      slug: "chattogram-civic-steps",
      title: "Chattogram Civic Steps",
      location: "Chattogram, Bangladesh",
      year: "2025",
      typology: "Civic Spaces",
      category: "landscape",
      subcategory: "civic-spaces",
      sizeM2: "12,600",
      heroImage: demoImage("photo-1500530855697-b586d89ba3ee"),
      description: "Demo public-realm project connecting a hillside neighborhood to the waterfront with shaded terraces.",
    },
    {
      id: "20",
      slug: "brahmaputra-growth-plan",
      title: "Brahmaputra Growth Plan",
      location: "Mymensingh, Bangladesh",
      year: "2026",
      typology: "Campus",
      category: "planning",
      subcategory: "campus",
      sizeM2: "145,000",
      heroImage: demoImage("photo-1500382017468-9049fed747ef"),
      description: "Demo campus framework aligning academic clusters, floodable landscapes, and low-carbon mobility.",
    },
    {
      id: "21",
      slug: "delta-regional-framework",
      title: "Delta Regional Framework",
      location: "Barisal Division, Bangladesh",
      year: "2025",
      typology: "Region",
      category: "planning",
      subcategory: "delta",
      sizeM2: "Regional scale",
      heroImage: demoImage("photo-1497366811353-6870744d04b2"),
      description: "Demo regional strategy mapping settlement, water infrastructure, and resilient growth across a river delta.",
    },
    {
      id: "22",
      slug: "dawn-pendant-light",
      title: "Dawn Pendant Light",
      location: "Dhaka, Bangladesh",
      year: "2026",
      typology: "Lighting",
      category: "products",
      subcategory: "lighting",
      sizeM2: "Product",
      heroImage: demoImage("photo-1505693416388-ac5ce068fe85"),
      description: "Demo pendant light exploring folded metal, warm reflected light, and a repairable modular assembly.",
    },
    {
      id: "23",
      slug: "delta-weave-chair",
      title: "Delta Weave Chair",
      location: "Dhaka, Bangladesh",
      year: "2025",
      typology: "Furniture",
      category: "products",
      subcategory: "furniture",
      sizeM2: "Product",
      heroImage: demoImage("photo-1598300056393-4aac492f4344"),
      description: "Demo chair concept combining a timber frame with replaceable woven seat and back panels.",
    },
    ] satisfies DemoProjectSeed[]).map(createDemoProject),
    ...([
      {
        id: "24",
        slug: "padma-river-arts-hall",
        title: "Padma River Arts Hall",
        location: "Rajshahi, Bangladesh",
        year: "2026",
        typology: "Culture",
        category: "architecture",
        subcategory: "culture",
        sizeM2: "7,800",
        heroImage: demoImage("photo-1511818966892-d7d671e672a2"),
        description: "Demo cultural venue using a shaded brick arcade to connect performance, workshop, and riverfront spaces.",
      },
      {
        id: "25",
        slug: "comilla-learning-courts",
        title: "Comilla Learning Courts",
        location: "Cumilla, Bangladesh",
        year: "2025",
        typology: "Education",
        category: "architecture",
        subcategory: "education",
        sizeM2: "5,400",
        heroImage: demoImage("photo-1600607687939-ce8a6c25118c"),
        description: "Demo school concept arranging bright classrooms around planted outdoor learning courts.",
      },
      {
        id: "26",
        slug: "sonargaon-community-clinic",
        title: "Sonargaon Community Clinic",
        location: "Sonargaon, Bangladesh",
        year: "2026",
        typology: "Health",
        category: "architecture",
        subcategory: "health",
        sizeM2: "2,900",
        heroImage: demoImage("photo-1600607687920-4e2a09cf159d"),
        description: "Demo neighborhood clinic planned around calm courtyards, shaded waiting areas, and clear circulation.",
      },
      {
        id: "27",
        slug: "kuakata-monsoon-house",
        title: "Kuakata Monsoon House",
        location: "Kuakata, Bangladesh",
        year: "2025",
        typology: "Residential",
        category: "architecture",
        subcategory: "residential",
        sizeM2: "1,960",
        heroImage: demoImage("photo-1600585154340-be6161a56a0c"),
        description: "Demo coastal home raised above seasonal water and protected by a deep, rain-shedding roof.",
      },
      {
        id: "28",
        slug: "dhanmondi-reading-room",
        title: "Dhanmondi Reading Room",
        location: "Dhaka, Bangladesh",
        year: "2025",
        typology: "Exhibition",
        category: "interiors",
        subcategory: "exhibition",
        sizeM2: "740",
        heroImage: demoImage("photo-1600210492486-724fe5c67fb0"),
        description: "Demo cultural interior with flexible display walls, a long reading table, and filtered daylight.",
      },
      {
        id: "29",
        slug: "riverstone-hotel-interiors",
        title: "Riverstone Hotel Interiors",
        location: "Narayanganj, Bangladesh",
        year: "2026",
        typology: "Hospitality",
        category: "interiors",
        subcategory: "hospitality",
        sizeM2: "3,200",
        heroImage: demoImage("photo-1600607687920-4e2a09cf159d"),
        description: "Demo hotel interiors using woven screens, tactile stone, and quiet views into a planted court.",
      },
      {
        id: "30",
        slug: "motijheel-studio-floor",
        title: "Motijheel Studio Floor",
        location: "Dhaka, Bangladesh",
        year: "2025",
        typology: "Workplace",
        category: "interiors",
        subcategory: "workplace",
        sizeM2: "1,480",
        heroImage: demoImage("photo-1616486338812-3dadae4b4ace"),
        description: "Demo office fit-out organizing focused work, shared tables, and small meeting rooms in one flexible floor.",
      },
      {
        id: "31",
        slug: "earth-and-water-gallery",
        title: "Earth and Water Gallery",
        location: "Khulna, Bangladesh",
        year: "2024",
        typology: "Exhibition",
        category: "interiors",
        subcategory: "exhibition",
        sizeM2: "1,120",
        heroImage: demoImage("photo-1600566753086-00f18fb6b3ea"),
        description: "Demo gallery arrangement for regional craft with adaptable display bays and a shaded entry court.",
      },
      {
        id: "32",
        slug: "hatirjheel-water-gardens",
        title: "Hatirjheel Water Gardens",
        location: "Dhaka, Bangladesh",
        year: "2026",
        typology: "Gardens",
        category: "landscape",
        subcategory: "gardens",
        sizeM2: "18,400",
        heroImage: demoImage("photo-1441974231531-c6227db76b6e"),
        description: "Demo lakeside landscape adding native wetland planting and shaded paths along the urban water edge.",
      },
      {
        id: "33",
        slug: "rangamati-hill-walk",
        title: "Rangamati Hill Walk",
        location: "Rangamati, Bangladesh",
        year: "2025",
        typology: "Parks",
        category: "landscape",
        subcategory: "parks",
        sizeM2: "11,700",
        heroImage: demoImage("photo-1470071459604-3b5ec3a7fe05"),
        description: "Demo hillside trail connecting lookout terraces, forest habitat, and a small community gathering space.",
      },
      {
        id: "34",
        slug: "bagerhat-civic-green",
        title: "Bagerhat Civic Green",
        location: "Bagerhat, Bangladesh",
        year: "2025",
        typology: "Civic Spaces",
        category: "landscape",
        subcategory: "civic-spaces",
        sizeM2: "8,600",
        heroImage: demoImage("photo-1500530855697-b586d89ba3ee"),
        description: "Demo public square pairing rain gardens with shaded seating and an open community lawn.",
      },
      {
        id: "35",
        slug: "tea-valley-restoration-park",
        title: "Tea Valley Restoration Park",
        location: "Sreemangal, Bangladesh",
        year: "2026",
        typology: "Parks",
        category: "landscape",
        subcategory: "parks",
        sizeM2: "27,000",
        heroImage: demoImage("photo-1511497584788-876760111969"),
        description: "Demo ecological park restoring native canopy and directing visitors along low-impact forest paths.",
      },
      {
        id: "36",
        slug: "barisal-waterfront-framework",
        title: "Barisal Waterfront Framework",
        location: "Barisal, Bangladesh",
        year: "2026",
        typology: "City",
        category: "planning",
        subcategory: "city",
        sizeM2: "City scale",
        heroImage: demoImage("photo-1480714378408-67cf0d13bc1b"),
        description: "Demo city strategy linking ferry access, floodable open space, and compact mixed-use streets.",
      },
      {
        id: "37",
        slug: "north-delta-settlement-plan",
        title: "North Delta Settlement Plan",
        location: "Kurigram, Bangladesh",
        year: "2025",
        typology: "Region",
        category: "planning",
        subcategory: "delta",
        sizeM2: "Regional scale",
        heroImage: demoImage("photo-1500382017468-9049fed747ef"),
        description: "Demo regional framework connecting resilient settlement clusters with water and transport networks.",
      },
      {
        id: "38",
        slug: "chattogram-university-precinct",
        title: "Chattogram University Precinct",
        location: "Chattogram, Bangladesh",
        year: "2026",
        typology: "Campus",
        category: "planning",
        subcategory: "campus",
        sizeM2: "86,000",
        heroImage: demoImage("photo-1518005020951-eccb494ad742"),
        description: "Demo campus plan sequencing academic buildings, shaded walks, and a continuous green commons.",
      },
      {
        id: "39",
        slug: "monsoon-table-collection",
        title: "Monsoon Table Collection",
        location: "Dhaka, Bangladesh",
        year: "2026",
        typology: "Furniture",
        category: "products",
        subcategory: "furniture",
        sizeM2: "Product",
        heroImage: demoImage("photo-1499933374294-4584851497cc"),
        description: "Demo furniture family built around repairable timber joints and compact proportions for urban homes.",
      },
      {
        id: "40",
        slug: "delta-fold-wall-light",
        title: "Delta Fold Wall Light",
        location: "Dhaka, Bangladesh",
        year: "2025",
        typology: "Lighting",
        category: "products",
        subcategory: "lighting",
        sizeM2: "Product",
        heroImage: demoImage("photo-1507473885765-e6ed057f782c"),
        description: "Demo wall light casting a soft wash through a folded shade made for easy replacement and repair.",
      },
      {
        id: "41",
        slug: "bamboo-rain-screen",
        title: "Bamboo Rain Screen",
        location: "Sylhet, Bangladesh",
        year: "2025",
        typology: "Installations",
        category: "products",
        subcategory: "installations",
        sizeM2: "Installation",
        heroImage: demoImage("photo-1511818966892-d7d671e672a2"),
        description: "Demo modular bamboo screen designed to filter sun and monsoon rain in a semi-open pavilion.",
      },
      {
        id: "42",
        slug: "delta-stool-series",
        title: "Delta Stool Series",
        location: "Dhaka, Bangladesh",
        year: "2024",
        typology: "Furniture",
        category: "products",
        subcategory: "furniture",
        sizeM2: "Product",
        heroImage: demoImage("photo-1598300056393-4aac492f4344"),
        description: "Demo stackable stools using a minimal timber frame and replaceable woven panels.",
      },
      {
        id: "43",
        slug: "riverstone-table-lamp",
        title: "Riverstone Table Lamp",
        location: "Dhaka, Bangladesh",
        year: "2025",
        typology: "Lighting",
        category: "products",
        subcategory: "lighting",
        sizeM2: "Product",
        heroImage: demoImage("photo-1507473885765-e6ed057f782c"),
        description: "Demo bedside lamp pairing a compact stone base with a low-glare translucent shade.",
      },
      {
        id: "44",
        slug: "six-starhitect-project",
        title: "6 Starhitect Project",
        location: "Dhaka, Bangladesh",
        year: "2026",
        typology: "Work",
        category: "architecture",
        subcategory: "work",
        sizeM2: "18,500",
        heroImage: demoImage("photo-1497366754035-f200968a6e72"),
        description: "Demo workplace concept exploring a clear structural grid, flexible team spaces, and generous daylight.",
      },
      {
        id: "45",
        slug: "corporate-offices",
        title: "Corporate Offices",
        location: "Dhaka, Bangladesh",
        year: "2025",
        typology: "Work",
        category: "architecture",
        subcategory: "work",
        sizeM2: "24,000",
        heroImage: demoImage("photo-1497366216548-37526070297c"),
        description: "Demo office campus pairing shared work floors with shaded courtyards and planted terraces.",
      },
      {
        id: "46",
        slug: "vehicle-assembly-plant",
        title: "Vehicle Assembly Plant",
        location: "Chattogram, Bangladesh",
        year: "2026",
        typology: "Infrastructure",
        category: "architecture",
        subcategory: "work",
        sizeM2: "42,000",
        heroImage: demoImage("photo-1487958449943-2429e8be8625"),
        description: "Demo industrial facility concept organizing production, logistics, and staff amenities under one clear roofscape.",
      },
      {
        id: "47",
        slug: "luxury-retreat-hotels",
        title: "Luxury Retreat Hotels",
        location: "Cox's Bazar, Bangladesh",
        year: "2025",
        typology: "Hospitality",
        category: "architecture",
        subcategory: "hospitality",
        sizeM2: "12,800",
        heroImage: demoImage("photo-1600566753190-17f0baa2a6c3"),
        description: "Demo retreat concept framing sea and garden views through quiet courtyards and sheltered guest wings.",
      },
      {
        id: "48",
        slug: "aviation-plant",
        title: "Aviation Fighter Jet Plant",
        location: "International",
        year: "2026",
        typology: "Infrastructure",
        category: "architecture",
        subcategory: "work",
        sizeM2: "56,000",
        heroImage: demoImage("photo-1613490493576-7fde63acd811"),
        description: "Demo aviation manufacturing concept separating assembly halls, research spaces, and secure service routes.",
      },
      {
        id: "49",
        slug: "architecture-schools",
        title: "Architecture Schools",
        location: "Dhaka, Bangladesh",
        year: "2025",
        typology: "Education",
        category: "architecture",
        subcategory: "education",
        sizeM2: "9,200",
        heroImage: demoImage("photo-1600047509807-ba8f99d2cdde"),
        description: "Demo learning environment linking studios, model workshops, and outdoor review spaces around a shared court.",
      },
      {
        id: "50",
        slug: "industrial-plant",
        title: "Industrial Plant",
        location: "Gazipur, Bangladesh",
        year: "2026",
        typology: "Infrastructure",
        category: "architecture",
        subcategory: "work",
        sizeM2: "38,000",
        heroImage: demoImage("photo-1565043589221-1a6fd9ae45c7"),
        description: "Demo production campus with legible circulation, adaptable bays, and a sheltered landscape edge.",
      },
      {
        id: "51",
        slug: "sports-stadiums",
        title: "Sports Stadiums",
        location: "Rajshahi, Bangladesh",
        year: "2025",
        typology: "Sports",
        category: "architecture",
        subcategory: "culture",
        sizeM2: "31,000",
        heroImage: demoImage("photo-1461896836934-ffe607ba8211"),
        description: "Demo stadium concept with shaded spectator routes and a welcoming public forecourt for event days.",
      },
      {
        id: "52",
        slug: "automotive-manufacturing-plant",
        title: "Automotive Manufacturing Plant",
        location: "Narayanganj, Bangladesh",
        year: "2026",
        typology: "Infrastructure",
        category: "architecture",
        subcategory: "work",
        sizeM2: "48,000",
        heroImage: demoImage("photo-1567789884554-0b844b597180"),
        description: "Demo automotive production campus balancing long-span assembly halls with daylight and worker amenities.",
      },
      {
        id: "53",
        slug: "robotics-factories",
        title: "Robotics Factories",
        location: "Dhaka, Bangladesh",
        year: "2026",
        typology: "Infrastructure",
        category: "architecture",
        subcategory: "work",
        sizeM2: "29,500",
        heroImage: demoImage("photo-1581091226825-a6a2a5aee158"),
        description: "Demo robotics facility bringing testing labs, production floors, and collaboration areas into one flexible plan.",
      },
      {
        id: "54",
        slug: "concert-and-opera-house",
        title: "Concert and Opera House",
        location: "Dhaka, Bangladesh",
        year: "2025",
        typology: "Culture",
        category: "architecture",
        subcategory: "culture",
        sizeM2: "16,200",
        heroImage: demoImage("photo-1470229722913-7c0e2dbbafd3"),
        description: "Demo performing arts venue organized around a welcoming foyer, adaptable halls, and acoustic rehearsal rooms.",
      },
      {
        id: "55",
        slug: "hotel-lobby-designs",
        title: "Hotel Lobby Designs",
        location: "Sylhet, Bangladesh",
        year: "2026",
        typology: "Hospitality",
        category: "interiors",
        subcategory: "hospitality",
        sizeM2: "1,850",
        heroImage: demoImage("photo-1618221195710-dd6b41faaea6"),
        description: "Demo lobby interior using layered seating, tactile finishes, and a direct visual connection to the garden.",
      },
      {
        id: "56",
        slug: "old-building-interior-transformation",
        title: "Old Building Interior Transformation",
        location: "Old Dhaka, Bangladesh",
        year: "2025",
        typology: "Exhibition",
        category: "interiors",
        subcategory: "exhibition",
        sizeM2: "2,400",
        heroImage: demoImage("photo-1600573472592-401b489a3cdc"),
        description: "Demo adaptive reuse study retaining the character of an old building while introducing flexible public rooms.",
      },
      {
        id: "57",
        slug: "nature-design-by-jeff-yen",
        title: "Nature Design by Jeff Yen",
        location: "International",
        year: "2025",
        typology: "Gardens",
        category: "landscape",
        subcategory: "gardens",
        sizeM2: "Landscape scale",
        heroImage: demoImage("photo-1497250681960-ef046c08a56e"),
        description: "Demo nature-led landscape concept combining native planting, quiet paths, and spaces for restoration.",
      },
      {
        id: "58",
        slug: "premium-car-repair-china",
        title: "Premium Car Repair Center, China",
        location: "China",
        year: "2026",
        typology: "Work",
        category: "architecture",
        subcategory: "work",
        sizeM2: "8,600",
        heroImage: demoImage("photo-1581092160562-40aa08e78837"),
        description: "Demo automotive service center with clear customer arrival, workshop circulation, and bright inspection bays.",
      },
      {
        id: "59",
        slug: "corporate-headquarters",
        title: "Corporate Headquarters",
        location: "Dhaka, Bangladesh",
        year: "2026",
        typology: "Work",
        category: "architecture",
        subcategory: "work",
        sizeM2: "33,000",
        heroImage: demoImage("photo-1524758631624-e2822e304c36"),
        description: "Demo headquarters concept shaped around a shaded civic entrance, flexible offices, and shared terraces.",
      },
      {
        id: "60",
        slug: "steel-structure-with-glass",
        title: "Steel Structure with Glass",
        location: "Chattogram, Bangladesh",
        year: "2025",
        typology: "Work",
        category: "architecture",
        subcategory: "work",
        sizeM2: "19,700",
        heroImage: demoImage("photo-1618005182384-a83a8bd57fbe"),
        description: "Demo steel-and-glass building study balancing open spans with deep shade and carefully framed views.",
      },
      {
        id: "61",
        slug: "exterior-designs-and-car-showrooms",
        title: "Exterior Designs and Car Showrooms",
        location: "Dhaka, Bangladesh",
        year: "2026",
        typology: "Work",
        category: "architecture",
        subcategory: "work",
        sizeM2: "6,300",
        heroImage: demoImage("photo-1552519507-da3b142c6e3d"),
        description: "Demo showroom concept giving vehicles a clear architectural setting with shaded display and service zones.",
      },
      {
        id: "62",
        slug: "landscape-design-by-masha",
        title: "Landscape Design by Masha",
        location: "International",
        year: "2025",
        typology: "Gardens",
        category: "landscape",
        subcategory: "gardens",
        sizeM2: "Landscape scale",
        heroImage: demoImage("photo-1513836279014-a89f7a76ae86"),
        description: "Demo garden design balancing naturalistic planting, outdoor rooms, and intimate paths through greenery.",
      },
      {
        id: "63",
        slug: "condo-buildings-forested-community",
        title: "Condo Buildings and Forested Community",
        location: "International",
        year: "2026",
        typology: "Residential",
        category: "architecture",
        subcategory: "residential",
        sizeM2: "46,000",
        heroImage: demoImage("photo-1510798831971-661eb04b3739"),
        description: "Demo residential community with low-rise homes set among preserved trees, shared gardens, and quiet paths.",
      },
    ] satisfies DemoProjectSeed[]).map(createDemoProject),
];

export const NEWS_ITEMS: NewsItem[] = [
  {
    id: "n1",
    slug: "dhaka-art-center-inauguration",
    title: "Dhaka Contemporary Art Center Celebrates Grand Opening",
    date: "MARCH 2026",
    author: "Plane Architect",
    sourceUrl: "https://www.facebook.com/share/1DemBySww5/?mibextid=wwXIfr",
    category: "Architecture",
    excerpt:
      "Plane Architect's 48,000 m² cultural complex on Dhaka's waterfront opens to the public, inaugurating new civic galleries and shaded water courtyards.",
    image:
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
    readTime: "4 min read",
  },
  {
    id: "n2",
    slug: "brahmaputra-campus-groundbreaking",
    title: "Groundbreaking Ceremony for Brahmaputra Ecological Campus",
    date: "FEBRUARY 2026",
    author: "Plane Architect",
    category: "Education",
    excerpt:
      "Construction begins on South Asia's largest engineered bamboo research campus in Mymensingh.",
    image:
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=800&q=80",
    readTime: "3 min read",
  },
  {
    id: "n3",
    slug: "gulshan-botanical-award",
    title: "Gulshan Botanical Pavilion Wins South Asian Urban Landscape Prize",
    date: "JANUARY 2026",
    author: "Plane Architect",
    category: "Landscape",
    excerpt:
      "Recognized for restoring native wetlands and introducing microclimatic thermal comfort to central Dhaka.",
    image:
      "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80",
    readTime: "5 min read",
  },
  {
    id: "n4",
    slug: "sustainability-monograph-release",
    title: "Plane Architect Publishes New Monograph: 'Geometry in the Delta'",
    date: "DECEMBER 2025",
    author: "Plane Architect",
    category: "Publications",
    excerpt:
      "A comprehensive review of 10 years of architectural research, flood resilience, and low-carbon materials in Bangladesh.",
    image:
      "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=800&q=80",
    readTime: "6 min read",
  },
];

export const CATEGORIES_CONFIG = [
  {
    id: "architecture",
    label: "Architecture",
    subcategories: [
      { id: "all", label: "View all", slug: "/projects" },
      { id: "culture", label: "Culture", slug: "/projects?type=culture" },
      { id: "education", label: "Education", slug: "/projects?type=education" },
      { id: "work", label: "Work", slug: "/projects?type=work" },
      { id: "hospitality", label: "Hospitality", slug: "/projects?type=hospitality" },
      { id: "residential", label: "Residential", slug: "/projects?type=residential" },
      { id: "infrastructure", label: "Infrastructure", slug: "/projects?type=infrastructure" },
    ],
  },
  {
    id: "interiors",
    label: "Interiors",
    subcategories: [
      { id: "all", label: "View all", slug: "/projects?cat=interiors" },
      { id: "workplace", label: "Workplace", slug: "/projects?cat=interiors&type=workplace" },
      { id: "hospitality", label: "Hospitality", slug: "/projects?cat=interiors&type=hospitality" },
      { id: "exhibition", label: "Exhibition", slug: "/projects?cat=interiors&type=exhibition" },
    ],
  },
  {
    id: "landscape",
    label: "Landscape",
    subcategories: [
      { id: "all", label: "View all", slug: "/projects?cat=landscape" },
      { id: "parks", label: "Parks", slug: "/projects?cat=landscape&type=parks" },
      { id: "civic-spaces", label: "Civic Spaces", slug: "/projects?cat=landscape&type=civic-spaces" },
      { id: "gardens", label: "Gardens", slug: "/projects?cat=landscape&type=gardens" },
    ],
  },
  {
    id: "planning",
    label: "Planning",
    subcategories: [
      { id: "all", label: "View all", slug: "/projects?cat=planning" },
      { id: "campus", label: "Campus", slug: "/projects?cat=planning&type=campus" },
      { id: "city", label: "City", slug: "/projects?cat=planning&type=city" },
      { id: "delta", label: "Delta Masterplans", slug: "/projects?cat=planning&type=delta" },
    ],
  },
  {
    id: "products",
    label: "Products",
    subcategories: [
      { id: "all", label: "View all", slug: "/projects?cat=products" },
      { id: "lighting", label: "Lighting", slug: "/projects?cat=products&type=lighting" },
      { id: "furniture", label: "Furniture", slug: "/projects?cat=products&type=furniture" },
      { id: "installations", label: "Installations", slug: "/projects?cat=products&type=installations" },
    ],
  },
];
